// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJkmdunD0D_moxvf_wBBoxOCu_Nrc3Kqs',
    appId: '1:160864015838:web:78e85b0e228bf65b3b794f',
    messagingSenderId: '160864015838',
    projectId: 'flutter-tareas-637db',
    authDomain: 'flutter-tareas-637db.firebaseapp.com',
    storageBucket: 'flutter-tareas-637db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZLhi_9lkCmo-pCfpPxHsPAJd9l0BNaw',
    appId: '1:160864015838:android:33dae1a2c95d80253b794f',
    messagingSenderId: '160864015838',
    projectId: 'flutter-tareas-637db',
    storageBucket: 'flutter-tareas-637db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCixOT91sWRf6ofCM8X6fJ0_IstAnW6EpU',
    appId: '1:160864015838:ios:29aaeeafaf8ec7963b794f',
    messagingSenderId: '160864015838',
    projectId: 'flutter-tareas-637db',
    storageBucket: 'flutter-tareas-637db.appspot.com',
    iosClientId: '160864015838-7v6j5tadn2nrliruc5vms4nsrclj25c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCixOT91sWRf6ofCM8X6fJ0_IstAnW6EpU',
    appId: '1:160864015838:ios:93d208899d014b563b794f',
    messagingSenderId: '160864015838',
    projectId: 'flutter-tareas-637db',
    storageBucket: 'flutter-tareas-637db.appspot.com',
    iosClientId: '160864015838-67bv91f8jjj1b1sajnhhfrpa4b3so5gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksApplication.RunnerTests',
  );
}
